### ISSUE TITLE
Support configurable index patterns

### ISSUE THREAD

**Issue by retzkek** [opensciencegrid/gracc-reporting#44]
The Elasticsearch index patterns that are queried are currently hardcoded in https://github.com/opensciencegrid/gracc-reporting/blob/master/src/graccreports/IndexPattern.py; this function should be generalized to accept a prefix as an argument, and then ideally the prefixes to use for raw and summary records could be specified in the config file (`[elasticsearch]` section?). This would support running reports for other GRACC streams, including in dev and non-osg installations.

**Comment by shreyb** [comment]
@retzkek and I were discussing this offline, but I'm putting it here for the record.  The idea with regard to the config file would be that we'd then have something like the following:

raw = "gracc.osg.raw"
summary = "gracc.osg.summary"

etc.

The index pattern function would then take the config value and attach date information as needed.  Perhaps we'd do config validation in the ReportUtils:Reporter.indexpattern_generate method

**Comment by shreyb** [comment]
This is now finished and will come out with the next release (which I'm hoping to cut today).

**Comment by shreyb** [comment]
This has been added to the 1.0 release.
